apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-demo
  namespace: vickey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-demo
  template:
    metadata:
      labels:
        app: tekton-demo
    spec:
      containers:
      - name: tekton-demo
        image: image-registry.openshift-image-registry.svc:5000/vickey/tekton-demo:latest
        ports:
        - containerPort: 8080
